### ISSUE TITLE
Possible Bug in migrations

### ISSUE THREAD

**Issue by oliveiraxavier** [Cherry-Pie/LogEnvelope#12]
I found a possible error in migration (exceptions table).
After run composer update, the script tryes run migration (ok). After this, i am run **php artisan migrate** for my table, its generate error "table exists".
My suggestion is  add the following lines to the migration file.

```
public function up()    {
        if (!Schema::hasTable('exceptions')) {
 ....
....

public function down()    {        
 	if (Schema::hasTable('exceptions')) {
....
 ...

```

**Comment by oliveiraxavier** [comment]
View https://github.com/Cherry-Pie/LogEnvelope/pull/13

**Comment by Cherry-Pie** [comment]
Thanks!
It's on 1.4.3 now
