### ISSUE TITLE
Debug is false

### ISSUE THREAD

**Issue by stanwarri** [Cherry-Pie/LogEnvelope#2]
Hello,

Does this work even when debug is set to false. I'm not getting any email when debug is set to false.

**Comment by Cherry-Pie** [comment]
Hai @stanwarri 
Yeah, you should receive when debug is disabled. Just checked and its ok.

Can you provide what Exception are you expecting?
Are you configured email sending and its not "pretend => true"?

**Comment by stanwarri** [comment]
I think it's working fine.
