### ISSUE TITLE
Queue-able

### ISSUE THREAD

**Issue by Cannonb4ll** [Cherry-Pie/LogEnvelope#3]
Is it possible to create a setting that we can make e-mails get queued? I don't want to have my clients to wait for a 'debug' e-mail to be send.

**Comment by Cherry-Pie** [comment]
@Cannonb4ll ofk, it'll be done by the end of this week

**Comment by Cannonb4ll** [comment]
Great mate, thanks!

**Comment by Cannonb4ll** [comment]
Create PR here: https://github.com/Cherry-Pie/LogEnvelope/pull/4
